# RSS 来源配置
# 添加新来源只需在此追加
# 支持的type: rss, pubmed

# ============================================================
# 一手源：顶级期刊 - Nature 系列
# ============================================================

- name: Nature
  type: rss
  url: https://www.nature.com/nature.rss

- name: Nature Neuroscience
  type: rss
  url: https://www.nature.com/neuro.rss

- name: Nature Genetics
  type: rss
  url: https://www.nature.com/ng/rss

- name: Nature Cell Biology
  type: rss
  url: https://www.nature.com/ncb.rss

- name: Nature Methods
  type: rss
  url: https://www.nature.com/nmeth.rss

- name: Nature Structural & Molecular Biology
  type: rss
  url: https://www.nature.com/nsmb.rss

- name: Nature Chemical Biology
  type: rss
  url: https://www.nature.com/nchembio.rss

- name: Nature Communications
  type: rss
  url: https://www.nature.com/ncomms.rss

- name: Nature Biotechnology
  type: rss
  url: https://www.nature.com/nbt.rss

- name: Nature Medicine
  type: rss
  url: https://www.nature.com/nm.rss

- name: Nature Reviews Molecular Cell Biology
  type: rss
  url: https://www.nature.com/nrm.rss

- name: Nature Reviews Genetics
  type: rss
  url: https://www.nature.com/nrg.rss

# ============================================================
# 一手源：顶级期刊 - Cell 系列
# ============================================================

- name: Cell
  type: rss
  url: https://www.cell.com/cell/current.rss

- name: Molecular Cell
  type: rss
  url: https://www.cell.com/molecular-cell/current.rss

- name: Cell Reports
  type: rss
  url: https://www.cell.com/cell-reports/current.rss

- name: Neuron
  type: rss
  url: https://www.cell.com/neuron/current.rss

- name: Cell Stem Cell
  type: rss
  url: https://www.cell.com/cell-stem-cell/current.rss

- name: Cancer Cell
  type: rss
  url: https://www.cell.com/cancer-cell/current.rss

- name: Immunity
  type: rss
  url: https://www.cell.com/immunity/current.rss

- name: Developmental Cell
  type: rss
  url: https://www.cell.com/developmental-cell/current.rss

- name: Cell Metabolism
  type: rss
  url: https://www.cell.com/cell-metabolism/current.rss

- name: Cell Chemical Biology
  type: rss
  url: https://www.cell.com/cell-chemical-biology/current.rss

# ============================================================
# 一手源：顶级期刊 - Science 系列
# ============================================================

- name: Science
  type: rss
  url: https://www.science.org/action/showFeed?type=etoc&feed=rss&jc=science
  enrich_via_pubmed: true
  enrich_min_content_len: 200  # RSS只有元数据，需要补充

- name: Science AOP
  type: rss
  url: https://www.science.org/action/showFeed?type=axatoc&feed=rss&jc=science
  enrich_via_pubmed: true
  enrich_min_content_len: 200

- name: Science Advances
  type: rss
  url: https://www.science.org/action/showFeed?type=etoc&feed=rss&jc=sciadv
  enrich_via_pubmed: true
  enrich_min_content_len: 200

- name: Science Signaling
  type: rss
  url: https://www.science.org/action/showFeed?type=etoc&feed=rss&jc=signaling
  enrich_via_pubmed: true
  enrich_min_content_len: 200

# ============================================================
# 一手源：其他顶级期刊
# ============================================================

- name: PNAS
  type: rss
  url: https://www.pnas.org/action/showFeed?type=etoc&feed=rss&jc=pnas
  enrich_via_pubmed: true

- name: eLife
  type: rss
  url: https://elifesciences.org/rss/recent.xml

- name: PLoS Biology
  type: rss
  url: https://journals.plos.org/plosbiology/feed/atom

- name: PLoS Genetics
  type: rss
  url: https://journals.plos.org/plosgenetics/feed/atom

- name: EMBO Journal
  type: rss
  url: https://www.embopress.org/action/showFeed?jc=emboj&type=etoc&feed=rss

- name: EMBO Reports
  type: rss
  url: https://www.embopress.org/action/showFeed?jc=embor&type=etoc&feed=rss

- name: Nucleic Acids Research
  type: rss
  url: https://academic.oup.com/rss/site_5127/3091.xml

# ============================================================
# 一手源：RNA 专业期刊
# ============================================================

- name: RNA
  type: rss
  url: https://rnajournal.cshlp.org/rss/current.xml

- name: RNA Biology
  type: rss
  url: https://www.tandfonline.com/feed/rss/krnb20

- name: Genes & Development
  type: rss
  url: https://genesdev.cshlp.org/rss/current.xml

# ============================================================
# 一手源：细胞/分子生物学期刊
# ============================================================

- name: Journal of Cell Biology
  type: rss
  url: https://rupress.org/jcb/rss/recent

- name: Journal of Biological Chemistry
  type: rss
  url: https://www.jbc.org/rss/recent.xml

- name: Current Biology
  type: rss
  url: https://www.cell.com/current-biology/current.rss

- name: Genome Research
  type: rss
  url: https://genome.cshlp.org/rss/current.xml

- name: Genome Biology
  type: rss
  url: https://genomebiology.biomedcentral.com/articles/most-recent/rss.xml

# ============================================================
# 一手源：预印本 (bioRxiv/medRxiv)
# ============================================================
# bioRxiv RSS: http://connect.biorxiv.org/biorxiv_xml.php?subject=<subject>
# 可选subject: all, animal_behavior, biochemistry, bioengineering, bioinformatics,
#   biophysics, cancer_biology, cell_biology, developmental_biology, ecology,
#   epidemiology, evolutionary_biology, genetics, genomics, immunology, microbiology,
#   molecular_biology, neuroscience, paleontology, pathology, pharmacology,
#   physiology, plant_biology, scientific_communication, synthetic_biology,
#   systems_biology, zoology

- name: bioRxiv Neuroscience
  type: rss
  url: http://connect.biorxiv.org/biorxiv_xml.php?subject=neuroscience

- name: bioRxiv Cell Biology
  type: rss
  url: http://connect.biorxiv.org/biorxiv_xml.php?subject=cell_biology

- name: bioRxiv Molecular Biology
  type: rss
  url: http://connect.biorxiv.org/biorxiv_xml.php?subject=molecular_biology

- name: bioRxiv Biochemistry
  type: rss
  url: http://connect.biorxiv.org/biorxiv_xml.php?subject=biochemistry

- name: bioRxiv Genetics
  type: rss
  url: http://connect.biorxiv.org/biorxiv_xml.php?subject=genetics

- name: bioRxiv Genomics
  type: rss
  url: http://connect.biorxiv.org/biorxiv_xml.php?subject=genomics

- name: bioRxiv Immunology
  type: rss
  url: http://connect.biorxiv.org/biorxiv_xml.php?subject=immunology

- name: bioRxiv Cancer Biology
  type: rss
  url: http://connect.biorxiv.org/biorxiv_xml.php?subject=cancer_biology

- name: bioRxiv Developmental Biology
  type: rss
  url: http://connect.biorxiv.org/biorxiv_xml.php?subject=developmental_biology

- name: bioRxiv Systems Biology
  type: rss
  url: http://connect.biorxiv.org/biorxiv_xml.php?subject=systems_biology

- name: bioRxiv Bioinformatics
  type: rss
  url: http://connect.biorxiv.org/biorxiv_xml.php?subject=bioinformatics

# ============================================================
# 一手源：PubMed 搜索
# ============================================================

# ------------------------------------------------------------
# 方案 C：生命科学大类 (用 MeSH 主题词，覆盖更全面)
# ------------------------------------------------------------

# 生命科学大类 - 使用 MeSH 主题词限定，不依赖关键词
- name: PubMed Life Sciences
  type: pubmed
  term: '("Molecular Biology"[MeSH] OR "Cell Biology"[MeSH] OR "Genetics"[MeSH] OR "Biochemistry"[MeSH] OR "Genomics"[MeSH] OR "Neurosciences"[MeSH] OR "Immunology"[MeSH] OR "Oncology"[MeSH]) AND hasabstract AND "last 2 days"[dp]'
  retmax: 2000

# 专项主题合并 - 你关注的研究方向
- name: PubMed Research Topics
  type: pubmed
  term: '(RTCB OR "tRNA ligase" OR "RNA ligase" OR "tRNA splicing" OR IRE1 OR XBP1 OR "unfolded protein response" OR "ER stress" OR "RNA splicing" OR spliceosome OR "m6A" OR "RNA modification" OR "RNA methylation" OR lncRNA OR circRNA OR "non-coding RNA" OR enhancer OR eRNA OR "super-enhancer" OR transposon OR retrotransposon OR "mobile element" OR CRISPR OR "gene editing") AND hasabstract AND "last 2 days"[dp]'
  retmax: 1000

# ------------------------------------------------------------
# 顶刊速报 (40个顶级期刊，抓取最新 ahead-of-print)
# ------------------------------------------------------------
- name: PubMed Top Journals
  type: pubmed
  term: '("Cell"[Journal] OR "Nature"[Journal] OR "Science"[Journal] OR "Molecular Cell"[Journal] OR "EMBO J"[Journal] OR "Genes Dev"[Journal] OR "Nucleic Acids Res"[Journal] OR "RNA"[Journal] OR "Nat Genet"[Journal] OR "Nat Cell Biol"[Journal] OR "Nat Struct Mol Biol"[Journal] OR "Nat Methods"[Journal] OR "Nat Chem Biol"[Journal] OR "Nat Commun"[Journal] OR "Nat Biotechnol"[Journal] OR "Nat Med"[Journal] OR "Nat Neurosci"[Journal] OR "Nat Immunol"[Journal] OR "Nat Rev Mol Cell Biol"[Journal] OR "Nat Rev Genet"[Journal] OR "Cell Rep"[Journal] OR "Cell Stem Cell"[Journal] OR "Cancer Cell"[Journal] OR "Immunity"[Journal] OR "Dev Cell"[Journal] OR "Cell Metab"[Journal] OR "Neuron"[Journal] OR "Curr Biol"[Journal] OR "eLife"[Journal] OR "PNAS"[Journal] OR "Proc Natl Acad Sci U S A"[Journal] OR "PLoS Biol"[Journal] OR "PLoS Genet"[Journal] OR "EMBO Rep"[Journal] OR "Mol Cell Biol"[Journal] OR "J Cell Biol"[Journal] OR "J Biol Chem"[Journal] OR "Genome Res"[Journal] OR "Genome Biol"[Journal] OR "Mol Syst Biol"[Journal]) AND hasabstract AND "last 2 days"[dp]'
  retmax: 500

# ============================================================
# 二手源：公众号 (需要第三方RSS服务)
# ============================================================
# 推荐服务:
# - Feeddd: https://feeddd.org/ (免费，需要关注公众号获取)
# - WeRSS: https://werss.app/ (付费)
# - RSSHub: https://docs.rsshub.app/routes/new-media#wei-xin (需自建)

# 取消注释并替换为实际的RSS URL:
# - name: BioArt
#   type: rss
#   url: https://feeddd.org/feeds/xxxxx  # 替换为实际URL
#
# - name: 科研圈
#   type: rss
#   url: https://feeddd.org/feeds/xxxxx  # 替换为实际URL
#
# - name: 知识分子
#   type: rss
#   url: https://feeddd.org/feeds/xxxxx  # 替换为实际URL

# ============================================================
# 二手源：科学新闻网站
# ============================================================

- name: Phys.org Biology
  type: rss
  url: https://phys.org/rss-feed/biology-news/

- name: Science Daily
  type: rss
  url: https://www.sciencedaily.com/rss/top/science.xml

- name: EurekAlert Life Sciences
  type: rss
  url: https://www.eurekalert.org/rss/biology.xml

# 科学网 (中文)
# - name: 科学网
#   type: rss
#   url: https://www.sciencenet.cn/xml/news.aspx?news=0  # 需确认是否可用

# ============================================================
# 补充期刊：结构/分子
# ============================================================

- name: Structure
  type: rss
  url: https://www.cell.com/structure/current.rss

- name: Molecular Biology of the Cell
  type: rss
  url: https://www.molbiolcell.org/action/showFeed?type=etoc&feed=rss&jc=mboc

# Journal of Molecular Biology - ScienceDirect 403
# Journal of Cell Science - Biologists.com 404

# ============================================================
# 补充期刊：生化
# ============================================================

- name: Biochemistry (ACS)
  type: rss
  url: https://pubs.acs.org/action/showFeed?type=axatoc&feed=rss&jc=bichaw

- name: FEBS Journal
  type: rss
  url: https://febs.onlinelibrary.wiley.com/feed/17424658/most-recent

- name: FEBS Letters
  type: rss
  url: https://febs.onlinelibrary.wiley.com/feed/18733468/most-recent

# Biochemical Journal - Portland Press 404

# ============================================================
# 补充期刊：遗传学
# ============================================================

# Genetics (GSA) - OUP 404
# Human Molecular Genetics - OUP 404

- name: American Journal of Human Genetics
  type: rss
  url: https://www.cell.com/ajhg/current.rss

# ============================================================
# 补充期刊：方法
# ============================================================

- name: Nature Protocols
  type: rss
  url: https://www.nature.com/nprot.rss

- name: Cell Reports Methods
  type: rss
  url: https://www.cell.com/cell-reports-methods/current.rss

# ============================================================
# 补充期刊：综述
# ============================================================

- name: Trends in Cell Biology
  type: rss
  url: https://www.cell.com/trends/cell-biology/current.rss

- name: Trends in Biochemical Sciences
  type: rss
  url: https://www.cell.com/trends/biochemical-sciences/current.rss

# Current Opinion in Cell Biology - Cell.com 404
# Current Opinion in Structural Biology - ScienceDirect 403
# Annual Review of Biochemistry - AnnualReviews 403
# Annual Review of Cell and Dev Biology - AnnualReviews 403

# ============================================================
# 补充期刊：开放获取
# ============================================================

- name: Communications Biology
  type: rss
  url: https://www.nature.com/commsbio.rss

# ============================================================
# 深度报道 & 科普
# ============================================================

- name: Quanta Magazine Biology
  type: rss
  url: https://quantamagazine.org/biology/feed/

# ============================================================
# API 源：bioRxiv/medRxiv 官方 API
# 解决 RSS 时效性问题，覆盖所有学科
#
# 30 天窗口确保不漏文章，seen.json 去重保护日常压力
# ============================================================

- name: bioRxiv API All
  type: biorxiv_api
  server: biorxiv
  days_back: 2  # 日常增量，回填用专门脚本

- name: medRxiv API All
  type: biorxiv_api
  server: medrxiv
  days_back: 2

# ============================================================
# API 源：OpenAlex (开放学术图谱)
# 覆盖 2.5 亿+ 论文，完全免费
# max_results 限制单次获取量，seen.json 负责去重
# ============================================================

- name: OpenAlex Molecular Biology
  type: openalex
  days_back: 2
  concepts:
    - molecular_biology
    - cell_biology
    - biochemistry
  max_results: 500
  open_access_only: false

- name: OpenAlex Genetics & Genomics
  type: openalex
  days_back: 2
  concepts:
    - genetics
    - genomics
    - gene_expression
  max_results: 500

- name: OpenAlex Neuroscience
  type: openalex
  days_back: 2
  concepts:
    - neuroscience
    - neurobiology
  max_results: 500

# 新增：更多领域覆盖
- name: OpenAlex Immunology
  type: openalex
  days_back: 2
  concepts:
    - immunology
    - immune_system
  max_results: 500

- name: OpenAlex Cancer
  type: openalex
  days_back: 2
  concepts:
    - cancer
    - oncology
    - tumor
  max_results: 500

- name: OpenAlex Microbiology
  type: openalex
  days_back: 2
  concepts:
    - microbiology
    - virology
    - bacteriology
  max_results: 500

- name: OpenAlex Developmental Biology
  type: openalex
  days_back: 2
  concepts:
    - developmental_biology
    - embryology
    - stem_cell
  max_results: 300

- name: OpenAlex Pharmacology
  type: openalex
  days_back: 2
  concepts:
    - pharmacology
    - drug_discovery
    - toxicology
  max_results: 300

# ============================================================
# API 源：Europe PMC (预印本 + PubMed 补充)
# 预印本收录比 PubMed 更及时
# ============================================================

- name: Europe PMC Preprints
  type: europepmc
  days_back: 2
  sources:
    - PPR  # 所有预印本服务器
  max_results: 800

# 新增：通用生医药搜索（去掉 RNA 限制）
- name: Europe PMC Cancer
  type: europepmc
  days_back: 2
  query: 'cancer OR tumor OR oncology OR carcinoma'
  sources:
    - MED
    - PPR
  max_results: 500

- name: Europe PMC Immunology
  type: europepmc
  days_back: 2
  query: 'immunology OR "immune response" OR inflammation OR autoimmune'
  sources:
    - MED
    - PPR
  max_results: 500

- name: Europe PMC Neuroscience
  type: europepmc
  days_back: 2
  query: 'neuroscience OR neuron OR brain OR neurodegeneration'
  sources:
    - MED
    - PPR
  max_results: 500

- name: Europe PMC Genetics
  type: europepmc
  days_back: 2
  query: 'genetics OR genomics OR GWAS OR "gene therapy"'
  sources:
    - MED
    - PPR
  max_results: 500

# 保留 RNA 研究（你的方向）
- name: Europe PMC RNA Research
  type: europepmc
  days_back: 2
  query: 'RNA OR "non-coding RNA" OR lncRNA OR miRNA OR tRNA'
  sources:
    - MED
    - PPR
  max_results: 300
