"""HTML output generator for ScholarPipe."""

import html
from datetime import datetime
from pathlib import Path
import hashlib

from ..models import NewsItem


def _get_fingerprint(item: NewsItem) -> str:
    """Generate a fingerprint for the item (simplified version)."""
    if item.doi:
        return f"doi:{item.doi}"
    title = (item.title or "").strip().lower()
    return hashlib.md5(title.encode()).hexdigest()[:16]


def to_html(items: list[NewsItem], stats: dict | None = None) -> str:
    """Generate a beautiful HTML page from news items."""
    today = datetime.now().strftime("%Y-%m-%d")

    # Group items by source
    sources = {}
    for item in items:
        source = item.source_name or "Other"
        if source not in sources:
            sources[source] = []
        sources[source].append(item)

    # Build HTML
    items_html = []
    for i, item in enumerate(items, 1):
        items_html.append(_render_card(item, i))

    html_content = f"""<!DOCTYPE html>
<html lang="zh-CN">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ScholarPipe | {today}</title>
    <style>
{_get_css()}
    </style>
</head>
<body>
    <div class="container">
        <header class="header">
            <h1>ScholarPipe</h1>
            <p class="subtitle">AI-Powered Academic Daily Digest</p>
            <div class="meta">
                <span class="date">{today}</span>
                <span class="count">{len(items)} articles</span>
            </div>
        </header>

        {_render_stats(stats) if stats else ""}

        <main class="articles">
            {"".join(items_html) if items else '<p class="empty">No articles for today</p>'}
        </main>

        <footer class="footer">
            <p>Generated by <strong>ScholarPipe</strong></p>
            <div class="feedback-export">
                <button onclick="exportFeedback()" class="export-btn">Export Feedback Data</button>
                <span id="feedback-count"></span>
            </div>
        </footer>
    </div>
    <script>
{_get_feedback_js()}
    </script>
</body>
</html>"""

    return html_content


def to_html_file(items: list[NewsItem], path: str, stats: dict | None = None) -> None:
    """Export items to HTML file."""
    html_content = to_html(items, stats)

    Path(path).parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(html_content)


def _render_card(item: NewsItem, index: int) -> str:
    """Render a single article card."""
    # VIP badge
    vip_badge = ""
    if item.is_vip:
        keywords = ", ".join(item.vip_keywords) if item.vip_keywords else "VIP"
        vip_badge = f'<span class="badge vip">{html.escape(keywords)}</span>'

    # Relevance score
    score_html = ""
    if item.semantic_score is not None:
        score_pct = int(item.semantic_score * 100)
        score_class = "high" if score_pct >= 70 else "medium" if score_pct >= 40 else "low"
        score_html = f'<span class="score {score_class}">{score_pct}%</span>'

    # Authors
    authors_html = ""
    if item.authors:
        authors_list = item.authors[:5]
        if len(item.authors) > 5:
            authors_str = ", ".join(authors_list) + f" et al. ({len(item.authors)})"
        else:
            authors_str = ", ".join(authors_list)
        authors_html = f'<p class="authors">{html.escape(authors_str)}</p>'

    # Summary or content excerpt
    summary = item.summary or item.content
    if summary:
        # Clean HTML tags for display
        import re
        summary = re.sub(r'<[^>]+>', '', summary)
        if len(summary) > 300:
            summary = summary[:300] + "..."
    else:
        summary = ""

    # Image
    image_html = ""
    img_url = item.image_url or (item.image_urls[0] if item.image_urls else "")
    if img_url:
        image_html = f'<div class="card-image"><img src="{html.escape(img_url)}" alt="" loading="lazy"></div>'

    # DOI badge
    doi_html = ""
    if item.doi:
        doi_html = f'<a href="https://doi.org/{html.escape(item.doi)}" class="doi" target="_blank">DOI: {html.escape(item.doi)}</a>'

    # Published date
    pub_date = ""
    if item.published_at:
        pub_date = item.published_at.strftime("%Y-%m-%d") if isinstance(item.published_at, datetime) else str(item.published_at)[:10]

    # Fingerprint for feedback
    fingerprint = _get_fingerprint(item)
    score_val = item.semantic_score or 0.0
    vip_kw_str = ",".join(item.vip_keywords) if item.vip_keywords else ""
    content_len = len(item.content or "")

    # Source display: show journal name for PubMed articles
    source_display = item.source_name or "Unknown"
    journal_html = ""
    if item.journal_name and item.source_name and item.source_name.startswith("PubMed"):
        journal_html = f'<span class="journal">@ {html.escape(item.journal_name)}</span>'

    return f"""
        <article class="card{' vip-card' if item.is_vip else ''}"
                 data-fp="{html.escape(fingerprint)}"
                 data-rank="{index}"
                 data-title="{html.escape(item.title or '')}"
                 data-source="{html.escape(item.source_name or '')}"
                 data-journal="{html.escape(item.journal_name or '')}"
                 data-score="{score_val}"
                 data-vip="{html.escape(vip_kw_str)}"
                 data-doi="{html.escape(item.doi or '')}"
                 data-enriched="{str(item.is_enriched).lower()}"
                 data-content-len="{content_len}"
                 data-has-image="{str(bool(item.image_url or item.image_urls)).lower()}"
                 data-authors-count="{len(item.authors)}"
                 data-link="{html.escape(item.link or '')}">
            <div class="card-header">
                <span class="index">#{index}</span>
                <span class="source">{html.escape(source_display)}</span>
                {journal_html}
                {vip_badge}
                {score_html}
            </div>
            {image_html}
            <div class="card-body">
                <h2 class="title">
                    <a href="{html.escape(item.link)}" target="_blank" onclick="trackClick(this)">{html.escape(item.title)}</a>
                </h2>
                {authors_html}
                <p class="summary">{html.escape(summary)}</p>
            </div>
            <div class="card-footer">
                {doi_html}
                <span class="date">{pub_date}</span>
                <div class="feedback-area">
                    <div class="feedback-btns">
                        <button class="fb-btn fb-up" onclick="recordFeedback(this, 'relevant')" title="Relevant">&#x1F44D;</button>
                        <button class="fb-btn fb-down" onclick="recordFeedback(this, 'irrelevant')" title="Not Relevant">&#x1F44E;</button>
                    </div>
                    <div class="feedback-comment">
                        <input type="text" class="fb-input" placeholder="Add comment..." maxlength="200">
                        <button class="fb-send" onclick="submitComment(this)" title="Submit comment">&#x27A4;</button>
                    </div>
                </div>
                <a href="{html.escape(item.link)}" class="read-more" target="_blank" onclick="trackClick(this)">Read More &rarr;</a>
            </div>
        </article>"""


def _render_stats(stats: dict) -> str:
    """Render statistics section."""
    total = stats.get('total', 0)
    after_dedup = stats.get('after_dedup', 0)
    after_filter = stats.get('after_filter', 0)

    return f"""
        <div class="stats">
            <div class="stat-item">
                <span class="stat-value">{total}</span>
                <span class="stat-label">Fetched</span>
            </div>
            <div class="stat-arrow">&rarr;</div>
            <div class="stat-item">
                <span class="stat-value">{after_dedup}</span>
                <span class="stat-label">Deduplicated</span>
            </div>
            <div class="stat-arrow">&rarr;</div>
            <div class="stat-item">
                <span class="stat-value">{after_filter}</span>
                <span class="stat-label">Filtered</span>
            </div>
        </div>"""


def _get_css() -> str:
    """Return the CSS styles."""
    return """
        :root {
            --primary: #2563eb;
            --primary-dark: #1d4ed8;
            --secondary: #64748b;
            --success: #10b981;
            --warning: #f59e0b;
            --danger: #ef4444;
            --bg: #f8fafc;
            --card-bg: #ffffff;
            --text: #1e293b;
            --text-muted: #64748b;
            --border: #e2e8f0;
            --shadow: 0 4px 6px -1px rgb(0 0 0 / 0.1), 0 2px 4px -2px rgb(0 0 0 / 0.1);
            --shadow-lg: 0 10px 15px -3px rgb(0 0 0 / 0.1), 0 4px 6px -4px rgb(0 0 0 / 0.1);
        }

        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, sans-serif;
            background: var(--bg);
            color: var(--text);
            line-height: 1.6;
            min-height: 100vh;
        }

        .container {
            max-width: 900px;
            margin: 0 auto;
            padding: 2rem 1rem;
        }

        .header {
            text-align: center;
            margin-bottom: 2rem;
            padding: 2rem;
            background: linear-gradient(135deg, var(--primary) 0%, var(--primary-dark) 100%);
            border-radius: 1rem;
            color: white;
        }

        .header h1 {
            font-size: 2.5rem;
            font-weight: 700;
            margin-bottom: 0.5rem;
            letter-spacing: -0.02em;
        }

        .header .subtitle {
            font-size: 1.1rem;
            opacity: 0.9;
            margin-bottom: 1rem;
        }

        .header .meta {
            display: flex;
            justify-content: center;
            gap: 1.5rem;
            font-size: 0.95rem;
        }

        .header .meta span {
            background: rgba(255,255,255,0.2);
            padding: 0.4rem 1rem;
            border-radius: 2rem;
        }

        .stats {
            display: flex;
            justify-content: center;
            align-items: center;
            gap: 1rem;
            margin-bottom: 2rem;
            padding: 1.5rem;
            background: var(--card-bg);
            border-radius: 0.75rem;
            box-shadow: var(--shadow);
        }

        .stat-item {
            text-align: center;
        }

        .stat-value {
            display: block;
            font-size: 1.75rem;
            font-weight: 700;
            color: var(--primary);
        }

        .stat-label {
            font-size: 0.85rem;
            color: var(--text-muted);
        }

        .stat-arrow {
            color: var(--text-muted);
            font-size: 1.25rem;
        }

        .articles {
            display: flex;
            flex-direction: column;
            gap: 1.5rem;
        }

        .card {
            background: var(--card-bg);
            border-radius: 0.75rem;
            box-shadow: var(--shadow);
            overflow: hidden;
            transition: transform 0.2s, box-shadow 0.2s;
        }

        .card:hover {
            transform: translateY(-2px);
            box-shadow: var(--shadow-lg);
        }

        .vip-card {
            border: 2px solid var(--warning);
        }

        .card-header {
            display: flex;
            align-items: center;
            gap: 0.75rem;
            padding: 1rem 1.25rem;
            background: var(--bg);
            border-bottom: 1px solid var(--border);
        }

        .card-header .index {
            font-weight: 600;
            color: var(--text-muted);
        }

        .card-header .source {
            font-size: 0.875rem;
            color: var(--primary);
            font-weight: 500;
        }

        .card-header .journal {
            font-size: 0.8rem;
            color: var(--success);
            font-weight: 500;
            font-style: italic;
        }

        .badge {
            font-size: 0.75rem;
            padding: 0.25rem 0.75rem;
            border-radius: 1rem;
            font-weight: 500;
        }

        .badge.vip {
            background: var(--warning);
            color: white;
        }

        .score {
            margin-left: auto;
            font-size: 0.875rem;
            font-weight: 600;
            padding: 0.25rem 0.75rem;
            border-radius: 1rem;
        }

        .score.high {
            background: #dcfce7;
            color: #166534;
        }

        .score.medium {
            background: #fef3c7;
            color: #92400e;
        }

        .score.low {
            background: #fee2e2;
            color: #991b1b;
        }

        .card-image {
            width: 100%;
            max-height: 250px;
            overflow: hidden;
        }

        .card-image img {
            width: 100%;
            height: 100%;
            object-fit: cover;
        }

        .card-body {
            padding: 1.25rem;
        }

        .card-body .title {
            font-size: 1.25rem;
            font-weight: 600;
            line-height: 1.4;
            margin-bottom: 0.75rem;
        }

        .card-body .title a {
            color: var(--text);
            text-decoration: none;
        }

        .card-body .title a:hover {
            color: var(--primary);
        }

        .card-body .authors {
            font-size: 0.9rem;
            color: var(--text-muted);
            margin-bottom: 0.75rem;
        }

        .card-body .summary {
            font-size: 0.95rem;
            color: var(--secondary);
            line-height: 1.7;
        }

        .card-footer {
            display: flex;
            align-items: center;
            gap: 1rem;
            padding: 1rem 1.25rem;
            background: var(--bg);
            border-top: 1px solid var(--border);
            font-size: 0.875rem;
        }

        .card-footer .doi {
            color: var(--text-muted);
            text-decoration: none;
            font-family: monospace;
            font-size: 0.8rem;
        }

        .card-footer .doi:hover {
            color: var(--primary);
        }

        .card-footer .date {
            color: var(--text-muted);
        }

        .card-footer .read-more {
            margin-left: auto;
            color: var(--primary);
            text-decoration: none;
            font-weight: 500;
        }

        .card-footer .read-more:hover {
            text-decoration: underline;
        }

        .feedback-area {
            display: flex;
            flex-direction: column;
            gap: 0.5rem;
        }

        .feedback-btns {
            display: flex;
            gap: 0.5rem;
        }

        .fb-btn {
            border: none;
            background: transparent;
            cursor: pointer;
            font-size: 1.25rem;
            padding: 0.25rem 0.5rem;
            border-radius: 0.375rem;
            transition: background 0.2s, transform 0.1s;
            opacity: 0.6;
        }

        .fb-btn:hover {
            opacity: 1;
            transform: scale(1.1);
        }

        .fb-btn.active {
            opacity: 1;
            background: var(--bg);
        }

        .fb-up.active {
            background: #dcfce7;
        }

        .fb-down.active {
            background: #fee2e2;
        }

        .feedback-comment {
            display: flex;
            gap: 0.375rem;
            align-items: center;
        }

        .fb-input {
            flex: 1;
            padding: 0.375rem 0.625rem;
            border: 1px solid var(--border);
            border-radius: 0.375rem;
            font-size: 0.8rem;
            min-width: 120px;
            transition: border-color 0.2s, box-shadow 0.2s;
        }

        .fb-input:focus {
            outline: none;
            border-color: var(--primary);
            box-shadow: 0 0 0 2px rgba(37, 99, 235, 0.1);
        }

        .fb-input.sent {
            background: #f0fdf4;
            border-color: var(--success);
        }

        .fb-send {
            border: none;
            background: var(--primary);
            color: white;
            cursor: pointer;
            font-size: 0.875rem;
            padding: 0.375rem 0.625rem;
            border-radius: 0.375rem;
            transition: background 0.2s, transform 0.1s;
        }

        .fb-send:hover {
            background: var(--primary-dark);
            transform: scale(1.05);
        }

        .fb-send:disabled {
            background: var(--secondary);
            cursor: not-allowed;
            transform: none;
        }

        .feedback-export {
            margin-top: 1rem;
        }

        .export-btn {
            background: var(--primary);
            color: white;
            border: none;
            padding: 0.5rem 1rem;
            border-radius: 0.375rem;
            cursor: pointer;
            font-size: 0.875rem;
            transition: background 0.2s;
        }

        .export-btn:hover {
            background: var(--primary-dark);
        }

        #feedback-count {
            margin-left: 0.5rem;
            font-size: 0.875rem;
            color: var(--text-muted);
        }

        .empty {
            text-align: center;
            padding: 3rem;
            color: var(--text-muted);
            font-size: 1.1rem;
        }

        .footer {
            text-align: center;
            padding: 2rem;
            margin-top: 2rem;
            color: var(--text-muted);
            font-size: 0.9rem;
        }

        @media (max-width: 640px) {
            .container {
                padding: 1rem;
            }

            .header {
                padding: 1.5rem;
            }

            .header h1 {
                font-size: 1.75rem;
            }

            .header .meta {
                flex-direction: column;
                gap: 0.5rem;
            }

            .stats {
                flex-wrap: wrap;
            }

            .card-body .title {
                font-size: 1.1rem;
            }

            .card-footer {
                flex-wrap: wrap;
            }
        }
    """


def _get_feedback_js() -> str:
    """Return the JavaScript for feedback handling."""
    return """
        const STORAGE_KEY = 'scholarpipe_feedback';

        function getFeedbackStore() {
            const data = localStorage.getItem(STORAGE_KEY);
            return data ? JSON.parse(data) : [];
        }

        function saveFeedbackStore(store) {
            localStorage.setItem(STORAGE_KEY, JSON.stringify(store));
            updateFeedbackCount();
        }

        function collectCardData(card) {
            return {
                fingerprint: card.dataset.fp,
                rank: parseInt(card.dataset.rank) || 0,
                title: card.dataset.title,
                source_name: card.dataset.source,
                journal_name: card.dataset.journal || '',
                semantic_score: parseFloat(card.dataset.score) || 0,
                vip_keywords: card.dataset.vip ? card.dataset.vip.split(',') : [],
                doi: card.dataset.doi || '',
                is_enriched: card.dataset.enriched === 'true',
                content_len: parseInt(card.dataset.contentLen) || 0,
                has_image: card.dataset.hasImage === 'true',
                authors_count: parseInt(card.dataset.authorsCount) || 0,
                link: card.dataset.link || ''
            };
        }

        function recordFeedback(btn, type) {
            const card = btn.closest('.card');
            const data = collectCardData(card);

            const entry = {
                ...data,
                feedback_type: type,
                timestamp: new Date().toISOString()
            };

            const store = getFeedbackStore();
            store.push(entry);
            saveFeedbackStore(store);

            // Update UI
            const btns = card.querySelectorAll('.fb-btn');
            btns.forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
        }

        function trackClick(link) {
            const card = link.closest('.card');
            const data = collectCardData(card);

            const entry = {
                ...data,
                feedback_type: 'clicked',
                timestamp: new Date().toISOString()
            };

            const store = getFeedbackStore();
            store.push(entry);
            saveFeedbackStore(store);
        }

        function submitComment(btn) {
            const card = btn.closest('.card');
            const input = card.querySelector('.fb-input');
            const comment = input.value.trim();

            if (!comment) {
                input.focus();
                return;
            }

            const data = collectCardData(card);
            const entry = {
                ...data,
                feedback_type: 'comment',
                comment: comment,
                timestamp: new Date().toISOString()
            };

            const store = getFeedbackStore();
            store.push(entry);
            saveFeedbackStore(store);

            // Visual feedback
            input.classList.add('sent');
            input.value = '';
            input.placeholder = 'Comment saved!';
            btn.disabled = true;

            setTimeout(() => {
                input.classList.remove('sent');
                input.placeholder = 'Add comment...';
                btn.disabled = false;
            }, 2000);
        }

        function exportFeedback() {
            const store = getFeedbackStore();
            if (store.length === 0) {
                alert('No feedback data to export.');
                return;
            }

            const blob = new Blob([JSON.stringify(store, null, 2)], {type: 'application/json'});
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = 'feedback_' + new Date().toISOString().split('T')[0] + '.json';
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
        }

        function updateFeedbackCount() {
            const store = getFeedbackStore();
            const counts = {relevant: 0, irrelevant: 0, clicked: 0, comment: 0};
            store.forEach(e => {
                if (counts[e.feedback_type] !== undefined) {
                    counts[e.feedback_type]++;
                }
            });

            const el = document.getElementById('feedback-count');
            if (el) {
                el.textContent = `(${counts.relevant} relevant, ${counts.irrelevant} irrelevant, ${counts.comment} comments, ${counts.clicked} clicks)`;
            }
        }

        function restoreFeedbackState() {
            const store = getFeedbackStore();
            const byFp = {};
            const commentsByFp = {};

            store.forEach(e => {
                if (e.feedback_type === 'relevant' || e.feedback_type === 'irrelevant') {
                    byFp[e.fingerprint] = e.feedback_type;
                }
                if (e.feedback_type === 'comment' && e.comment) {
                    if (!commentsByFp[e.fingerprint]) {
                        commentsByFp[e.fingerprint] = [];
                    }
                    commentsByFp[e.fingerprint].push(e.comment);
                }
            });

            document.querySelectorAll('.card').forEach(card => {
                const fp = card.dataset.fp;
                if (byFp[fp]) {
                    const btnClass = byFp[fp] === 'relevant' ? '.fb-up' : '.fb-down';
                    const btn = card.querySelector(btnClass);
                    if (btn) btn.classList.add('active');
                }
                // Show comment count if any
                if (commentsByFp[fp] && commentsByFp[fp].length > 0) {
                    const input = card.querySelector('.fb-input');
                    if (input) {
                        input.placeholder = `${commentsByFp[fp].length} comment(s) saved`;
                    }
                }
            });
        }

        // Initialize on page load
        document.addEventListener('DOMContentLoaded', function() {
            updateFeedbackCount();
            restoreFeedbackState();

            // Enter key to submit comment
            document.querySelectorAll('.fb-input').forEach(input => {
                input.addEventListener('keypress', function(e) {
                    if (e.key === 'Enter') {
                        const btn = this.closest('.feedback-comment').querySelector('.fb-send');
                        submitComment(btn);
                    }
                });
            });
        });
    """
